import getpass
import os
import tempfile
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path


_EARTHKIT_CONFIG_FILE_ENV = "EARTHKIT_DATA_CONFIG_FILE"
_EARTHML_MANAGED_CONFIG_ENV = "EARTHML_MANAGED_EARTHKIT_CONFIG"


def configure_sources_runtime() -> None:
    _configure_earthkit_config_file()


def _configure_earthkit_config_file() -> None:
    current = os.environ.get(_EARTHKIT_CONFIG_FILE_ENV)
    managed = os.environ.get(_EARTHML_MANAGED_CONFIG_ENV) == "1"

    if current and not managed:
        return

    config_root = (
        Path(tempfile.gettempdir())
        / f"earthml-{getpass.getuser()}"
        / "earthkit-config"
        / f"pid-{os.getpid()}"
    )
    config_root.mkdir(parents=True, exist_ok=True)

    config_file = config_root / "config.yaml"
    _ensure_earthkit_config_file(config_file)

    os.environ[_EARTHKIT_CONFIG_FILE_ENV] = str(config_file)
    os.environ[_EARTHML_MANAGED_CONFIG_ENV] = "1"


def _ensure_earthkit_config_file(config_file: Path) -> None:
    """Create a minimal config before earthkit-data imports it.

    Dask worker processes can import earthkit-data concurrently. If all workers
    inherit the same managed config path, earthkit-data may observe an empty or
    partially initialized file and then fail comparing a missing version.
    """
    if config_file.exists() and config_file.stat().st_size > 0:
        return

    try:
        earthkit_version = version("earthkit-data")
    except PackageNotFoundError:
        earthkit_version = "0"

    tmp_config_file = config_file.with_suffix(f"{config_file.suffix}.{os.getpid()}.tmp")
    tmp_config_file.write_text(
        "# This file is automatically generated\n\n"
        "# Version of earthkit-data\n\n"
        f"version: {earthkit_version}\n",
        encoding="utf-8",
    )
    os.replace(tmp_config_file, config_file)
