from pathlib import Path
from typing import Literal, Sequence, cast
from dataclasses import dataclass

from datetime import datetime

import numpy as np
import pandas as pd
import xarray as xr

import earthml

from dask.diagnostics.progress import ProgressBar

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.colors import (
    BoundaryNorm,
    TwoSlopeNorm,
    LogNorm,
    Colormap,
    to_rgb,
)
from matplotlib.patches import Rectangle, Polygon
from matplotlib.ticker import FuncFormatter
from matplotlib.font_manager import FontProperties

from cmap import Colormap as CmapColormap

import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.mpl.geoaxes import GeoAxes
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER

from ..base import Settings, ClimPeriod
from ..metrics.definitions import ImprovementUnit

from .defaults import (
    DEFAULT_IMPROVEMENT_PLOT_CONFIG,
    DEFAULT_PLOT_CONFIG,
    VARIABLE_NAMES,
    VARIABLE_UNITS,
    UNIT_CONVERSIONS,
    SQUARED_METRICS,
    METRIC_NAMES,
    METRIC_UNITS,
    MODEL_COLORS,
    SERIES_COLORS,
    TRANSLATION_TABLE,
)


def safe_label(x: object) -> str:
    if x is None:
        return "all"
    return str(x).translate(TRANSLATION_TABLE)


def is_skill_metric(metric: str) -> bool:
    return (
        metric.endswith("_skill_clim")
        or metric.startswith("roc_")
        or metric in (
            "corr",
            "acc",
            "acc_spatial",
            "r2",
            "r2_anom",
            "spread_skill_ratio",
        )
    )

def is_skill_model(model: str) -> bool:
    return "_vs_" in model


def get_improvement_unit_from_model(
    model: str,
) -> ImprovementUnit | None:
    """Return the improvement representation encoded in a model name.

    Comparison names generated by ``build_metric_improvements`` end in
    ``_percentage``, ``_difference`` or ``_normalized``. Ordinary model
    names return ``None``.
    """
    if not is_skill_model(model):
        return None

    if model.endswith("_percentage"):
        return "%"

    if model.endswith("_difference"):
        return "Δ"

    if model.endswith("_normalized"):
        return "normalized"

    raise ValueError(
        f"Cannot determine improvement representation from model {model!r}."
    )


def get_plot_config(
    var: str,
    metric: str,
    var_plot_config: dict,
) -> dict:
    if metric not in DEFAULT_PLOT_CONFIG:
        raise KeyError(f"No default plot config for metric {metric!r}")

    cfg = DEFAULT_PLOT_CONFIG[metric].copy()
    cfg.update(var_plot_config.get(var, {}).get(metric, {}))
    return cfg

def get_skill_plot_config(
    var: str,
    metric: str,
    var_plot_config: dict,
    impro_plot_config: dict,
    improvement_unit: ImprovementUnit | None = None,
) -> dict:
    if improvement_unit is None:
        raise ValueError(
            f"improvement_unit must be explicitly provided "
            f"for metric {metric!r}"
        )

    cfg = DEFAULT_IMPROVEMENT_PLOT_CONFIG[
        improvement_unit
    ].copy()

    custom_cfg = (
        impro_plot_config
        .get(var, {})
        .get(metric, {})
    )

    if any(
        unit in custom_cfg
        for unit in ("%", "Δ", "normalized")
    ):
        cfg.update(
            custom_cfg.get(
                improvement_unit,
                {},
            )
        )
    else:
        cfg.update(custom_cfg)

    return cfg


def lead_label(
    da: xr.DataArray,
    lead_value,
    leadtime_dim: str = "leadtime",
) -> str:
    if "seasonal_leadtime" not in da.coords:
        return str(lead_value)

    labels = da.coords["seasonal_leadtime"]

    if leadtime_dim in labels.dims:
        return str(labels.sel({leadtime_dim: lead_value}).item())

    return str(labels.item())


def select_metric(
    ds: xr.Dataset,
    *,
    var: str,
    metric: str,
    model: str,
    start_period: str | int = "all",
) -> xr.DataArray:
    da = ds[var]

    if "metric" in da.dims:
        da = da.sel(metric=metric)

    if "model" in da.dims:
        da = da.sel(model=model)

    if "start_period" in da.dims:
        da = da.sel(start_period=start_period)

    return da

def convert_to_da_list(
    ds: xr.DataArray | xr.Dataset | Sequence[xr.DataArray | xr.Dataset | None] | None,
    var: str,
) -> list[xr.DataArray | None]:
    if ds is None:
        return []

    if isinstance(ds, xr.DataArray):
        return [ds]

    if isinstance(ds, xr.Dataset):
        return [ds[var]]

    if isinstance(ds, Sequence) and not isinstance(ds, (str, bytes)):
        result: list[xr.DataArray | None] = []

        for d in ds:
            if d is None:
                result.append(None)
            elif isinstance(d, xr.Dataset):
                result.append(d[var])
            elif isinstance(d, xr.DataArray):
                result.append(d)
            else:
                raise TypeError(f"Type {type(d)} not supported.")

        return result

    raise TypeError(f"Type {type(ds)} not supported.")



def adapt_colorbar_tick_sizes(
    fig,
    cb,
    *,
    tick_size: float | None = None,
    min_scale: float = 0.50,
    shrink_step: float = 0.95,
    spacing_px: float = 3.0,
) -> None:
    """Shrink colorbar labels, then alternate top/bottom if still crowded."""

    if tick_size is None:
        tick_size = FontProperties(
            size=plt.rcParams["xtick.labelsize"]
        ).get_size_in_points()

    min_size = tick_size * min_scale
    current_size = tick_size

    labels = (
        cb.ax.get_xticklabels()
        if cb.orientation == "horizontal"
        else cb.ax.get_yticklabels()
    )

    # ------------------------------------------------------------------
    # First try uniform shrinking.
    # ------------------------------------------------------------------
    while current_size >= min_size:

        for label in labels:
            label.set_fontsize(current_size)

        fig.canvas.draw()
        renderer = fig.canvas.get_renderer()

        bboxes = [
            label.get_window_extent(renderer)
            for label in labels
            if label.get_visible() and label.get_text()
        ]

        if cb.orientation == "horizontal":
            bboxes.sort(key=lambda bbox: bbox.x0)

            overlaps = any(
                a.x1 + spacing_px > b.x0
                for a, b in zip(bboxes[:-1], bboxes[1:])
            )
        else:
            bboxes.sort(key=lambda bbox: bbox.y0)

            overlaps = any(
                a.y1 + spacing_px > b.y0
                for a, b in zip(bboxes[:-1], bboxes[1:])
            )

        if not overlaps:
            return

        current_size *= shrink_step

    # ------------------------------------------------------------------
    # Still crowded: alternate horizontal labels bottom / top.
    # ------------------------------------------------------------------
    if cb.orientation == "horizontal":

        cb.ax.xaxis.set_ticks_position("both")

        cb.ax.tick_params(
            axis="x",
            which="major",
            top=True,
            bottom=True,
            labeltop=True,
            labelbottom=True,
            labelsize=min_size,
            pad=2,
        )

        fig.canvas.draw()

        ticks = cb.ax.xaxis.get_major_ticks()

        for i, tick in enumerate(ticks):

            # Both labels initially contain the same formatted value.
            tick.label1.set_fontsize(min_size)
            tick.label2.set_fontsize(min_size)

            if i % 2 == 0:
                # Bottom
                tick.label1.set_visible(True)
                tick.label2.set_visible(False)
            else:
                # Top
                tick.label1.set_visible(False)
                tick.label2.set_visible(True)

        # Some extra space from cobar and plot above
        pos = cb.ax.get_position()
        cb.ax.set_position([
            pos.x0,
            pos.y0 - 0.02,
            pos.width,
            pos.height,
        ])

    else:
        # Vertical colorbar: just enforce minimum size.
        for label in labels:
            label.set_fontsize(min_size)

    fig.canvas.draw()


def smart_tick_formatter(ticks):
    ticks = np.asarray(ticks, dtype=float)

    finite_ticks = np.sort(
        np.unique(ticks[np.isfinite(ticks)])
    )

    if finite_ticks.size == 0:
        return lambda x, _: str(x)

    # ----------------------------------------------------------
    # Fixed-point representation
    # ----------------------------------------------------------

    fixed_precision = 0

    while (
        np.unique(
            np.round(finite_ticks, fixed_precision)
        ).size
        < finite_ticks.size
    ):
        fixed_precision += 1

    def fixed_format(x):
        if np.isclose(x, 0):
            return "0"

        label = f"{x:.{fixed_precision}f}"

        if "." in label:
            label = label.rstrip("0").rstrip(".")

        return label

    # ----------------------------------------------------------
    # Scientific representation
    # ----------------------------------------------------------

    def scientific_format(x, precision):
        if np.isclose(x, 0):
            return "0"

        return (
            f"{x:.{precision}e}"
            .replace("e+0", "e+")
            .replace("e-0", "e-")
            .replace("e+", "e")
        )

    sci_precision = 0

    while (
        len(
            {
                scientific_format(
                    x,
                    sci_precision,
                )
                for x in finite_ticks
            }
        )
        < finite_ticks.size
    ):
        sci_precision += 1

    # ----------------------------------------------------------
    # Choose shortest representation
    # ----------------------------------------------------------

    fixed_labels = [
        fixed_format(x)
        for x in finite_ticks
    ]

    scientific_labels = [
        scientific_format(
            x,
            sci_precision,
        )
        for x in finite_ticks
    ]

    fixed_length = max(
        map(len, fixed_labels)
    )

    scientific_length = max(
        map(len, scientific_labels)
    )

    use_scientific = (
        scientific_length
        < fixed_length
    )

    def formatter(x, _):
        if use_scientific:
            return scientific_format(
                x,
                sci_precision,
            )

        return fixed_format(x)

    return formatter


def add_max_size_colorbar(
    fig,
    ax,
    im,
    *,
    ticks=None,
    pad: float = 0.055,
    size: float = 0.018,
):
    fig.canvas.draw()

    pos = ax.get_position()

    if pos.width >= pos.height:
        cax = fig.add_axes([
            pos.x0,
            pos.y0 - pad - size,
            pos.width,
            size,
        ])
        orientation = "horizontal"

    else:
        cax = fig.add_axes([
            pos.x1 + pad,
            pos.y0,
            size,
            pos.height,
        ])
        orientation = "vertical"

    return fig.colorbar(
        im,
        cax=cax,
        orientation=orientation,
        ticks=ticks,
    )


def add_spatial_regions(
    ax,
    regions: Sequence[dict] | None,
) -> None:
    if not regions:
        return

    for region in regions:
        region_type = region.get("type", "rectangle")

        common_kwargs = {
            "edgecolor": region.get("edgecolor", "black"),
            "facecolor": region.get("facecolor", "none"),
            "linewidth": region.get("linewidth", 2),
            "linestyle": region.get("linestyle", "-"),
            "transform": ccrs.PlateCarree(),
            "zorder": region.get("zorder", 10),
        }

        if region_type == "rectangle":
            lon_min, lon_max = region["lon_range"]
            lat_max, lat_min = region["lat_range"]

            patch = Rectangle(
                (lon_min, lat_min),
                lon_max - lon_min,
                lat_max - lat_min,
                **common_kwargs,
            )

            default_label_position = (
                (lon_min + lon_max) / 2,
                lat_max,
            )

        elif region_type == "polygon":
            coordinates = region["coordinates"]

            patch = Polygon(
                coordinates,
                closed=True,
                **common_kwargs,
            )

            coords = np.asarray(coordinates)

            default_label_position = (
                float(coords[:, 0].mean()),
                float(coords[:, 1].max()),
            )

        else:
            raise ValueError(
                f"Unsupported region type {region_type!r}. "
                "Choose 'rectangle' or 'polygon'."
            )

        ax.add_patch(patch)

        # Optional region name
        name = region.get("name")

        if name is not None:
            label_lon, label_lat = region.get(
                "label_position",
                default_label_position,
            )

            ax.text(
                label_lon,
                label_lat,
                name,
                transform=ccrs.PlateCarree(),
                ha=region.get("label_ha", "center"),
                va=region.get("label_va", "bottom"),
                fontsize=region.get("label_size", 10),
                color=region.get("label_color", "black"),
                zorder=region.get("label_zorder", 11),
            )


def metric_style(
    var: str,
    metric: str,
    da: xr.DataArray | None = None,
    *,
    var_plot_config: dict | None = None,
    impro_plot_config: dict | None = None,
    is_skill: bool = False,
    improvement_unit: ImprovementUnit | None = None,
) -> tuple[Colormap, BoundaryNorm | TwoSlopeNorm | LogNorm, np.ndarray]:
    var_plot_config = var_plot_config or {}
    impro_plot_config = impro_plot_config or {}

    try:
        if is_skill:
            cfg = get_skill_plot_config(
                var,
                metric,
                var_plot_config,
                impro_plot_config,
                improvement_unit=improvement_unit,
            )
        else:
            cfg = get_plot_config(var, metric, var_plot_config)

    except KeyError:
        if da is None:
            raise

        vmin = float(da.quantile(0.02, skipna=True))
        vmax = float(da.quantile(0.98, skipna=True))
        ticks = np.linspace(vmin, vmax, 11)
        cmap = plt.get_cmap("viridis")
        norm = BoundaryNorm(
            boundaries=ticks,
            ncolors=cmap.N,
            clip=False,
        )
        return cmap, norm, ticks

    tick_cfg = cfg["ticks"]

    if isinstance(tick_cfg, int):
        ticks = np.linspace(
            cfg["vmin"],
            cfg["vmax"],
            tick_cfg,
        )
    else:
        ticks = np.asarray(
            tick_cfg,
            dtype=float,
        )

    if is_skill:
        if not cfg["vmin"] < 0 < cfg["vmax"]:
            raise ValueError(
                f"Skill/improvement plot for {metric!r} requires "
                f"vmin < 0 < vmax, got "
                f"vmin={cfg['vmin']}, vmax={cfg['vmax']}"
            )

        norm = TwoSlopeNorm(
            vmin=cfg["vmin"],
            vcenter=0.0,
            vmax=cfg["vmax"],
        )

    elif metric in {
        "std_ratio",
        "std_ratio_anom",
        "regression_slope",
        "regression_slope_anom",
        "spread_skill_ratio",
        "spread_anom_skill_ratio",
    }:
        norm = LogNorm(
            vmin=cfg["vmin"],
            vmax=cfg["vmax"],
        )

    else:
        norm = BoundaryNorm(
            boundaries=ticks,
            ncolors=cfg["cmap"].N,
            clip=True,
        )

    return cfg["cmap"], norm, ticks


def get_plot_metric_unit_and_scale(
    da: xr.DataArray,
    *,
    var: str,
    metric: str,
    var_plot_config: dict,
) -> tuple[str, float]:
    cfg = get_plot_config(var, metric, var_plot_config)

    if not cfg.get("scale_units", True):
        return "", 1.0

    unit = da.attrs.get("units") or VARIABLE_UNITS.get(var, "")

    unit_conversion = UNIT_CONVERSIONS.get(unit, (unit, 1.0))
    if isinstance(unit_conversion, dict):
        plot_unit, scale = unit_conversion[var]
    else:
        plot_unit, scale = unit_conversion

    if metric in SQUARED_METRICS:
        return f"{plot_unit}²", scale**2

    return plot_unit, scale


def plot_profile(
    das: xr.DataArray | xr.Dataset | Sequence[xr.DataArray | xr.Dataset],
    *,
    var: str,
    metric: str,
    models: str | Sequence[str],
    labels: str | Sequence[str] | None = None,
    out_file: Path,
    time_range: tuple[str, str],
    profile_dim: str = "leadtime",
    profile_label: str,
    select_dim: str | None = "start_date",
    select_value: str | int | float | Sequence[str | int | float] = "all",
    select_unit: str | None = "months",
    select_colors: Literal["shades", "colors"] = "shades",
    das_member: xr.DataArray | xr.Dataset | Sequence[xr.DataArray | xr.Dataset | None] | None = None,
    realization_dim: str = "realization",
    spread: Literal["std", "minmax"] = "std",
    plot_single_members: bool = False,
    ylim: tuple[float, float] | None = None,
    plot_title: bool = True,
    plot_labels: bool = True,
    title_strftime: str = "%Y",
    plot_legend: bool = True,
    improvement_unit: ImprovementUnit | None = None,
    var_plot_config: dict | None = None,
    force_scale: int | float | None = None,
    model_colors: dict[str, object] | None = None,
    model_linestyles: dict[str, str] | None = None,

    # Categorical/profile-axis styling
    profile_point_colors: dict[str, object] | None = None,
    profile_markers: bool = False,
    profile_marker_size: float = 50,
    profile_connect: bool = True,
    profile_tick_rotation: float = 0,
    profile_zero_line: bool = False,

    figsize: tuple[float, float] = (12.0, 8.0),
    title_size: float | None = None,
    label_size: float | None = None,
    tick_size: float | None = None,
    dpi: int = 200,
) -> None:
    """Plot one or more 1-D metric profiles.

    ``profile_dim`` is the dimension shown on the x axis.
    ``profile_label`` explicitly defines the x-axis label.

    Examples
    --------
    Lead-time profile:
        profile_dim="leadtime"
        select_dim="start_month"
        select_value="all"

    Climatological monthly profile:
        profile_dim="month"
        select_dim="leadtime"
        select_value=<leadtime>

    ``improvement_unit`` should be passed explicitly for combined comparison
    plots whose curve labels are experiment names. For ordinary comparison
    names generated by ``build_metric_improvements`` it is inferred from the
    model-name suffix when possible.
    """

    var_plot_config = var_plot_config or {}

    model_list = (
        [models]
        if isinstance(models, str)
        else list(models)
    )

    label_list = (
        model_list
        if labels is None
        else (
            [labels]
            if isinstance(labels, str)
            else list(labels)
        )
    )

    if len(label_list) != len(model_list):
        raise ValueError(
            "Select the same number of labels and models. "
            f"Got {len(label_list)} labels and "
            f"{len(model_list)} models."
        )

    plot_das = convert_to_da_list(
        das,
        var,
    )

    if len(model_list) != len(plot_das):
        raise ValueError(
            "Select the same number of models and profile DataArrays. "
            f"Got {len(model_list)} models and "
            f"{len(plot_das)} DataArrays."
        )

    if das_member is None:
        plot_das_member = [None] * len(plot_das)

    else:
        plot_das_member = convert_to_da_list(
            das_member,
            var,
        )

        if len(plot_das_member) != len(plot_das):
            raise ValueError(
                "Select the same number of profile and member DataArrays. "
                f"Got {len(plot_das)} profiles and "
                f"{len(plot_das_member)} member arrays."
            )

    # ----------------------------------------------------------
    # Improvement representation
    # ----------------------------------------------------------

    if improvement_unit is None:
        inferred_units = {
            unit
            for model in model_list
            if (
                unit := get_improvement_unit_from_model(
                    model
                )
            )
            is not None
        }

        if len(inferred_units) > 1:
            raise ValueError(
                "All curves in one profile must use the same "
                "improvement representation, got "
                f"{sorted(inferred_units)!r}."
            )

        if inferred_units:
            improvement_unit = next(
                iter(inferred_units)
            )

    sample_da = next(
        (
            da
            for da in plot_das
            if da is not None
        ),
        None,
    )

    if sample_da is None:
        raise ValueError(
            "No profile DataArray is available to plot."
        )

    if improvement_unit in {
        "%",
        "normalized",
    }:
        plot_unit = (
            "%"
            if improvement_unit == "%"
            else ""
        )
        scale = 1.0

    else:
        plot_unit, scale = (
            get_plot_metric_unit_and_scale(
                sample_da,
                var=var,
                metric=metric,
                var_plot_config=var_plot_config,
            )
        )

    if force_scale is not None:
        scale = float(force_scale)

    # ----------------------------------------------------------
    # Selection values
    # ----------------------------------------------------------

    select_values = (
        list(select_value)
        if (
            isinstance(
                select_value,
                Sequence,
            )
            and not isinstance(
                select_value,
                (str, bytes),
            )
        )
        else [select_value]
    )

    n_select = len(select_values)

    color_cycle = plt.rcParams["axes.prop_cycle"].by_key()["color"]

    fig, ax = plt.subplots(
        figsize=figsize,
    )

    def _get_profile_x(
        profile: xr.DataArray,
    ) -> tuple[np.ndarray, np.ndarray | None]:
        """Return plottable x values and optional categorical labels."""

        values = np.asarray(
            profile[profile_dim].values
        )

        if values.dtype.kind in {"U", "S", "O"}:
            return (
                np.arange(values.size),
                values,
            )

        return values, None

    # ----------------------------------------------------------
    # Models
    # ----------------------------------------------------------

    for (
        model,
        label,
        da,
        da_member,
    ) in zip(
        model_list,
        label_list,
        plot_das,
        plot_das_member,
        strict=True,
    ):

        base_color = (
            model_colors[model]
            if (
                model_colors is not None
                and model in model_colors
            )
            else MODEL_COLORS.get(model)
        )

        linestyle = (
            model_linestyles.get(
                model,
                "-",
            )
            if model_linestyles is not None
            else "-"
        )

        # ------------------------------------------------------
        # Main profiles
        # ------------------------------------------------------

        if da is not None:

            for i, value in enumerate(
                select_values
            ):
                profile = da

                if select_dim is not None:
                    if select_dim not in profile.dims:
                        raise ValueError(
                            f"Selection dimension "
                            f"{select_dim!r} not found "
                            f"in profile dimensions "
                            f"{profile.dims}."
                        )

                    profile = profile.sel(
                        {
                            select_dim:
                                value
                        }
                    )

                if profile_dim not in profile.dims:
                    raise ValueError(
                        f"Profile dimension "
                        f"{profile_dim!r} not found "
                        f"in profile dimensions "
                        f"{profile.dims}."
                    )

                extra_dims = [
                    dim
                    for dim in profile.dims
                    if dim != profile_dim
                ]

                if extra_dims:
                    raise ValueError(
                        "Unexpected dimensions remain "
                        "before plotting profile: "
                        f"{extra_dims}. Expected only "
                        f"{profile_dim!r}, "
                        f"got {profile.dims}."
                    )

                with ProgressBar():
                    profile = (
                        profile
                        .reset_coords(
                            drop=True
                        )
                        .compute()
                        / scale
                    )

                x, categorical_labels = _get_profile_x(
                    profile
                )

                # Short lead times lighter,
                # long lead times darker.
                color = base_color

                if n_select > 1:
                    if select_colors == "shades":
                        if base_color is not None:
                            shade_amount = (
                                0.65
                                * (n_select - 1 - i)
                                / max(1, n_select - 1)
                            )

                            color = lighten(
                                base_color,
                                shade_amount,
                            )

                    elif select_colors == "colors":
                        color = color_cycle[i % len(color_cycle)]

                    else:
                        raise ValueError(
                            f"Unsupported select_colors={select_colors!r}. "
                            "Choose 'shades' or 'colors'."
                        )

                if (
                    n_select > 1
                    and base_color is not None
                ):
                    shade_amount = (
                        0.65
                        * (n_select - 1 - i)
                        / max(1, n_select - 1)
                    )

                    color = lighten(
                        base_color,
                        shade_amount,
                    )

                curve_label = label

                if profile_connect:
                    ax.plot(
                        x,
                        profile.values,
                        linestyle=linestyle,
                        linewidth=1.4,
                        label=curve_label,
                        color=color,
                    )

                if profile_markers:
                    for j, (xpos, coord_value, yvalue) in enumerate(
                        zip(
                            x,
                            profile[profile_dim].values,
                            profile.values,
                            strict=True,
                        )
                    ):
                        point_color = (
                            profile_point_colors.get(
                                str(coord_value),
                                color,
                            )
                            if profile_point_colors is not None
                            else color
                        )

                        ax.scatter(
                            xpos,
                            yvalue,
                            s=profile_marker_size,
                            color=point_color,
                            zorder=3,
                            label=(
                                curve_label
                                if not profile_connect and j == 0
                                else None
                            ),
                        )

        # ------------------------------------------------------
        # Ensemble/member profiles
        # ------------------------------------------------------

        if (
            da_member is None
            or realization_dim
            not in da_member.dims
        ):
            continue

        for i, value in enumerate(
            select_values
        ):
            member_profile = da_member

            if select_dim is not None:
                if (
                    select_dim
                    not in member_profile.dims
                ):
                    raise ValueError(
                        f"Selection dimension "
                        f"{select_dim!r} not found "
                        f"in member profile dimensions "
                        f"{member_profile.dims}."
                    )

                member_profile = (
                    member_profile.sel(
                        {
                            select_dim:
                                value
                        }
                    )
                )

            if (
                profile_dim
                not in member_profile.dims
            ):
                raise ValueError(
                    f"Profile dimension "
                    f"{profile_dim!r} not found "
                    f"in member profile dimensions "
                    f"{member_profile.dims}."
                )

            extra_dims = [
                dim
                for dim in member_profile.dims
                if dim not in {
                    profile_dim,
                    realization_dim,
                }
            ]

            if extra_dims:
                raise ValueError(
                    "Unexpected dimensions remain "
                    "before plotting member profile: "
                    f"{extra_dims}. Expected only "
                    f"{profile_dim!r} and "
                    f"{realization_dim!r}, "
                    f"got {member_profile.dims}."
                )

            with ProgressBar():
                member_profile = (
                    member_profile
                    .reset_coords(
                        drop=True
                    )
                    .compute()
                    / scale
                )

            x, _ = _get_profile_x(
                member_profile
            )

            color = base_color

            if n_select > 1:
                if select_colors == "shades":
                    if base_color is not None:
                        shade_amount = (
                            0.65
                            * (n_select - 1 - i)
                            / max(1, n_select - 1)
                        )

                        color = lighten(
                            base_color,
                            shade_amount,
                        )

                elif select_colors == "colors":
                    color = color_cycle[i % len(color_cycle)]

                else:
                    raise ValueError(
                        f"Unsupported select_colors={select_colors!r}. "
                        "Choose 'shades' or 'colors'."
                    )

            if plot_single_members:
                for j in range(
                    member_profile.sizes[
                        realization_dim
                    ]
                ):
                    ax.plot(
                        x,
                        member_profile.isel(
                            {realization_dim: j}
                        ).values,
                        linewidth=0.6,
                        alpha=0.25,
                        color=color,
                    )

            member_mean = (
                member_profile.mean(
                    realization_dim,
                    skipna=True,
                )
            )

            if spread == "std":
                member_spread = (
                    member_profile.std(
                        realization_dim,
                        skipna=True,
                    )
                )

                lower = member_mean - member_spread
                upper = member_mean + member_spread

            elif spread == "minmax":
                lower = (
                    member_profile.min(
                        realization_dim,
                        skipna=True,
                    )
                )

                upper = (
                    member_profile.max(
                        realization_dim,
                        skipna=True,
                    )
                )

            else:
                raise ValueError(
                    f"Unsupported spread="
                    f"{spread!r}. "
                    "Choose 'std' or 'minmax'."
                )

            ax.fill_between(
                x,
                lower.values,
                upper.values,
                alpha=0.18,
                color=color,
            )

            member_label = (
                f"{label} member mean"
            )

            if n_select > 1:
                unit = (
                    select_unit[:1].upper()
                    if select_unit
                    else ""
                )

                member_label = (
                    f"{member_label} · "
                    f"{value}{unit}"
                )

            ax.plot(
                x,
                member_mean.values,
                linewidth=1.4,
                linestyle="--",
                label=member_label,
                color=color,
            )

    # ----------------------------------------------------------
    # Y label / metric title
    # ----------------------------------------------------------

    metric_name = METRIC_NAMES.get(
        metric,
        metric,
    )

    if improvement_unit == "%":
        title_metric = (
            f"{metric_name} improvement"
        )

        ylabel = (
            f"{metric_name} improvement [%]"
        )

    elif improvement_unit == "Δ":
        title_metric = (
            f"{metric_name} "
            "improvement difference"
        )

        ylabel = (
            f"{metric_name} "
            f"improvement difference "
            f"[{plot_unit}]"
            if plot_unit
            else (
                f"{metric_name} "
                "improvement difference"
            )
        )

    elif improvement_unit == "normalized":
        title_metric = (
            f"{metric_name} "
            "normalized improvement"
        )

        ylabel = title_metric

    else:
        metric_unit = METRIC_UNITS.get(
            metric,
            "",
        )

        metric_unit = (
            metric_unit.format(
                unit=plot_unit
            )
            if metric_unit
            else ""
        )

        title_metric = metric_name

        ylabel = (
            f"{metric_name} "
            f"[{metric_unit}]"
            if metric_unit
            else metric_name
        )

    # ----------------------------------------------------------
    # Title
    # ----------------------------------------------------------

    if plot_title:
        start_time = datetime.strptime(
            time_range[0],
            "%Y-%m-%d",
        ).strftime(
            title_strftime
        )

        end_time = datetime.strptime(
            time_range[1],
            "%Y-%m-%d",
        ).strftime(
            title_strftime
        )

        selection_label = ""

        if (
            select_dim is not None
            and n_select == 1
            and select_values[0] != "all"
        ):
            unit = (
                select_unit[:1].upper()
                if select_unit
                else ""
            )

            selection_label = (
                f" · {select_dim}="
                f"{select_values[0]}"
                f"{unit}"
            )

        ax.set_title(
            f"{VARIABLE_NAMES[var]} · "
            f"{title_metric} · "
            f"{start_time}-{end_time}"
            f"{selection_label}",
            fontsize=title_size,
        )

    # ----------------------------------------------------------
    # X axis
    # ----------------------------------------------------------

    month_labels = [
        "Jan",
        "Feb",
        "Mar",
        "Apr",
        "May",
        "Jun",
        "Jul",
        "Aug",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
    ]

    if profile_dim.endswith("month"):

        ax.set_xticks(
            np.arange(1, 13)
        )

        ax.set_xticklabels(
            month_labels
        )

        if plot_labels:
            ax.set_xlabel(
                profile_label,
                fontsize=label_size,
            )

    elif profile_dim.endswith("dayofyear"):

        month_ticks = np.array(
            [
                pd.Timestamp(
                    2001,
                    month,
                    15,
                ).dayofyear
                for month in range(1, 13)
            ]
        )

        ax.set_xticks(
            month_ticks
        )

        ax.set_xticklabels(
            month_labels
        )

        if plot_labels:
            ax.set_xlabel(
                profile_label,
                fontsize=label_size,
            )

    elif profile_dim in {
        "leadtime",
        "leadtime_seasonal",
    }:

        leadtime_values = np.asarray(
            sample_da[profile_dim].values
        )

        ax.set_xticks(
            leadtime_values
        )

        formatter = smart_tick_formatter(leadtime_values)
        ax.set_xticklabels(
            [
                formatter(float(value), None)
                for value in leadtime_values
            ]
        )

        if plot_labels:
            ax.set_xlabel(
                profile_label,
                fontsize=label_size,
            )

    elif np.asarray(
        sample_da[profile_dim].values
    ).dtype.kind in {"U", "S", "O"}:

        categorical_values = np.asarray(
            sample_da[profile_dim].values
        )

        ax.set_xticks(
            np.arange(categorical_values.size)
        )

        ax.set_xticklabels(
            categorical_values,
            rotation=profile_tick_rotation,
            ha=(
                "right"
                if profile_tick_rotation
                else "center"
            ),
        )

        if plot_labels:
            ax.set_xlabel(
                profile_label,
                fontsize=label_size,
            )

    else:

        if plot_labels:
            ax.set_xlabel(
                profile_label,
                fontsize=label_size,
            )

    # ----------------------------------------------------------
    # Y axis / legend
    # ----------------------------------------------------------

    if ylim is not None:
        ax.set_ylim(*ylim)

    if plot_labels:
        ax.set_ylabel(
            ylabel,
            fontsize=label_size,
        )

    ax.tick_params(
        axis="both",
        labelsize=tick_size,
    )

    if profile_zero_line:
        ax.axhline(
            0.0,
            linewidth=1.0,
            linestyle="--",
            alpha=0.6,
        )

    ax.grid(True, alpha=0.3)

    if plot_legend:
        ax.legend()

    # ----------------------------------------------------------
    # Save
    # ----------------------------------------------------------

    out_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fig.tight_layout()

    fig.savefig(
        out_file,
        dpi=dpi,
        bbox_inches="tight",
    )

    plt.close(fig)


def plot_timeseries(
    das: xr.DataArray | xr.Dataset | Sequence[xr.DataArray | xr.Dataset],
    *,
    var: str,
    metric: str,
    models: str | Sequence[str],
    labels: str | Sequence[str] | None = None,
    out_file: Path,
    time_range: tuple[str, str],
    lead_value: object | None = None,
    leadtime_dim: str = "leadtime",
    time_dim: str | None = None,
    das_member: (
        xr.DataArray
        | xr.Dataset
        | Sequence[xr.DataArray | xr.Dataset | None]
        | None
    ) = None,
    realization_dim: str = "realization",
    spread: Literal["std", "minmax"] = "std",
    plot_single_members: bool = False,
    ylim: tuple[float, float] | None = None,
    plot_title: bool = True,
    plot_labels: bool = True,
    plot_legend: bool = True,
    title_strftime: str = "%Y",
    improvement_unit: ImprovementUnit | None = None,
    var_plot_config: dict | None = None,
    force_scale: int | float | None = None,
    model_colors: dict[str, object] | None = None,
    model_linestyles: dict[str, str] | None = None,
    timeseries_zero_line: bool = False,
    figsize: tuple[float, float] = (12.0, 6.0),
    title_size: float | None = None,
    label_size: float | None = None,
    tick_size: float | None = None,
    dpi: int = 200,
) -> None:
    """Plot one or more metric time series."""

    var_plot_config = var_plot_config or {}

    model_list = (
        [models]
        if isinstance(models, str)
        else list(models)
    )

    label_list = (
        model_list
        if labels is None
        else (
            [labels]
            if isinstance(labels, str)
            else list(labels)
        )
    )

    if len(label_list) != len(model_list):
        raise ValueError(
            "Select the same number of labels and models. "
            f"Got {len(label_list)} labels and "
            f"{len(model_list)} models."
        )

    plot_das = convert_to_da_list(
        das,
        var,
    )

    if len(plot_das) != len(model_list):
        raise ValueError(
            "Select the same number of models and timeseries DataArrays. "
            f"Got {len(model_list)} models and "
            f"{len(plot_das)} DataArrays."
        )

    if das_member is None:
        plot_das_member = [None] * len(plot_das)
    else:
        plot_das_member = convert_to_da_list(
            das_member,
            var,
        )

        if len(plot_das_member) != len(plot_das):
            raise ValueError(
                "Select the same number of timeseries and member DataArrays."
            )

    # ----------------------------------------------------------
    # Improvement representation
    # ----------------------------------------------------------

    if improvement_unit is None:
        inferred_units = {
            unit
            for model in model_list
            if (
                unit := get_improvement_unit_from_model(model)
            )
            is not None
        }

        if len(inferred_units) > 1:
            raise ValueError(
                "All curves in one timeseries must use the same "
                "improvement representation."
            )

        if inferred_units:
            improvement_unit = next(iter(inferred_units))

    sample_da = next(
        (
            da
            for da in plot_das
            if da is not None
        ),
        None,
    )

    if sample_da is None:
        raise ValueError(
            "No timeseries DataArray is available to plot."
        )

    # ----------------------------------------------------------
    # Determine time dimension
    # ----------------------------------------------------------

    if time_dim is None:
        time_dim = sample_da.earthml.guessed_dims.time

    if time_dim is None:
        raise ValueError(
            "Could not determine time dimension."
        )

    # ----------------------------------------------------------
    # Metric units / scaling
    # ----------------------------------------------------------

    if improvement_unit in {
        "%",
        "normalized",
    }:
        plot_unit = (
            "%"
            if improvement_unit == "%"
            else ""
        )
        scale = 1.0

    else:
        plot_unit, scale = get_plot_metric_unit_and_scale(
            sample_da,
            var=var,
            metric=metric,
            var_plot_config=var_plot_config,
        )

    if force_scale is not None:
        scale = float(force_scale)

    # ----------------------------------------------------------
    # Figure
    # ----------------------------------------------------------

    fig, ax = plt.subplots(
        figsize=figsize,
    )

    for (
        model,
        label,
        da,
        da_member,
    ) in zip(
        model_list,
        label_list,
        plot_das,
        plot_das_member,
        strict=True,
    ):
        if da is None:
            continue

        series = da

        if (
            lead_value is not None
            and leadtime_dim in series.dims
        ):
            series = series.sel(
                {leadtime_dim: lead_value}
            )

        series = series.squeeze(drop=True)

        if time_dim not in series.dims:
            raise ValueError(
                f"Time dimension {time_dim!r} not found in "
                f"timeseries dimensions {series.dims}."
            )

        extra_dims = [
            dim
            for dim in series.dims
            if dim != time_dim
        ]

        if extra_dims:
            raise ValueError(
                "Unexpected dimensions remain before plotting timeseries: "
                f"{extra_dims}. Expected only {time_dim!r}, "
                f"got {series.dims}."
            )

        with ProgressBar():
            series = (
                series
                .reset_coords(drop=True)
                .compute()
                / scale
            )

        color = (
            model_colors[model]
            if (
                model_colors is not None
                and model in model_colors
            )
            else MODEL_COLORS.get(model)
        )

        linestyle = (
            model_linestyles.get(
                model,
                "-",
            )
            if model_linestyles is not None
            else "-"
        )

        x = series[time_dim].values

        ax.plot(
            x,
            series.values,
            linewidth=1.4,
            linestyle=linestyle,
            label=label,
            color=color,
        )

        # ------------------------------------------------------
        # Ensemble/member spread
        # ------------------------------------------------------

        if (
            da_member is None
            or realization_dim not in da_member.dims
        ):
            continue

        member_series = da_member

        if (
            lead_value is not None
            and leadtime_dim in member_series.dims
        ):
            member_series = member_series.sel(
                {leadtime_dim: lead_value}
            )

        member_series = member_series.squeeze(drop=True)

        extra_dims = [
            dim
            for dim in member_series.dims
            if dim not in {
                time_dim,
                realization_dim,
            }
        ]

        if extra_dims:
            raise ValueError(
                "Unexpected dimensions remain before plotting "
                f"member timeseries: {extra_dims}."
            )

        with ProgressBar():
            member_series = (
                member_series
                .reset_coords(drop=True)
                .compute()
                / scale
            )

        if plot_single_members:
            for i in range(
                member_series.sizes[realization_dim]
            ):
                ax.plot(
                    x,
                    member_series.isel(
                        {realization_dim: i}
                    ).values,
                    linewidth=0.6,
                    alpha=0.25,
                    color=color,
                )

        member_mean = member_series.mean(
            realization_dim,
            skipna=True,
        )

        if spread == "std":
            member_spread = member_series.std(
                realization_dim,
                skipna=True,
            )
            lower = member_mean - member_spread
            upper = member_mean + member_spread

        elif spread == "minmax":
            lower = member_series.min(
                realization_dim,
                skipna=True,
            )
            upper = member_series.max(
                realization_dim,
                skipna=True,
            )

        else:
            raise ValueError(
                f"Unsupported spread={spread!r}. "
                "Choose 'std' or 'minmax'."
            )

        ax.fill_between(
            x,
            lower.values,
            upper.values,
            alpha=0.18,
            color=color,
        )

    # ----------------------------------------------------------
    # Labels
    # ----------------------------------------------------------

    metric_name = METRIC_NAMES.get(
        metric,
        metric,
    )

    if improvement_unit == "%":
        title_metric = (
            f"{metric_name} improvement"
        )
        ylabel = (
            f"{metric_name} improvement [%]"
        )

    elif improvement_unit == "Δ":
        title_metric = (
            f"{metric_name} improvement difference"
        )
        ylabel = (
            f"{title_metric} [{plot_unit}]"
            if plot_unit
            else title_metric
        )

    elif improvement_unit == "normalized":
        title_metric = (
            f"{metric_name} normalized improvement"
        )
        ylabel = title_metric

    else:
        metric_unit = METRIC_UNITS.get(
            metric,
            "",
        )

        metric_unit = (
            metric_unit.format(
                unit=plot_unit
            )
            if metric_unit
            else ""
        )

        title_metric = metric_name

        ylabel = (
            f"{metric_name} [{metric_unit}]"
            if metric_unit
            else metric_name
        )

    if plot_title:
        start_time = datetime.strptime(
            time_range[0],
            "%Y-%m-%d",
        ).strftime(
            title_strftime
        )

        end_time = datetime.strptime(
            time_range[1],
            "%Y-%m-%d",
        ).strftime(
            title_strftime
        )

        lead_label_str = ""

        if lead_value is not None:
            lead_label_str = (
                f" · leadtime="
                f"{lead_label(sample_da, lead_value, leadtime_dim)}"
            )

        ax.set_title(
            f"{VARIABLE_NAMES[var]} · "
            f"{title_metric} · "
            f"{start_time}-{end_time}"
            f"{lead_label_str}",
            fontsize=title_size,
        )

    if plot_labels:
        ax.set_xlabel(
            "Time",
            fontsize=label_size,
        )

        ax.set_ylabel(
            ylabel,
            fontsize=label_size,
        )

    if ylim is not None:
        ax.set_ylim(*ylim)

    ax.tick_params(
        axis="both",
        labelsize=tick_size,
    )

    if timeseries_zero_line:
        ax.axhline(
            0.0,
            linewidth=1.0,
            linestyle="--",
            alpha=0.6,
        )

    ax.grid(
        True,
        alpha=0.3,
    )

    if plot_legend:
        ax.legend()

    # ----------------------------------------------------------
    # Save
    # ----------------------------------------------------------

    out_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fig.tight_layout()

    fig.savefig(
        out_file,
        dpi=dpi,
        bbox_inches="tight",
    )

    plt.close(fig)


def plot_map(
    da: xr.DataArray,
    *,
    var: str,
    metric: str,
    model: str,
    start_period: str | int,
    lead_value: object,
    out_file: Path,
    time_range: tuple[str, str],
    plot_kind: Literal["maps", "time_lon", "time_lat"] = "maps",
    plot_type: Literal["pcolormesh", "contourf"] = "pcolormesh",
    leadtime_dim: str = "leadtime",
    leadtime_units: str = "months",
    period_dim: str = "start_month",
    clim_period: ClimPeriod | None = None,
    var_plot_config: dict | None = None,
    impro_plot_config: dict | None = None,
    force_scale: int | float | None = None,
    regions: Sequence[dict] | None = None,
    plot_title: bool = True,
    plot_labels: bool = True,
    title_strftime: str = "%Y",
    significance: xr.DataArray | None = None,
    significance_stride: int = 3,
    significance_size: float = 2.0,
    significance_alpha: float = 0.6,
    title_size: float | None = None,
    label_size: float | None = None,
    tick_size: float | None = None,
    dpi: int = 300,
) -> None:
    var_plot_config = var_plot_config or {}
    impro_plot_config = impro_plot_config or {}

    improvement_unit = get_improvement_unit_from_model(model)
    is_skill = improvement_unit is not None

    time_dim = da.earthml.guessed_dims.time or clim_period
    lat, lon = da.earthml.guessed_dims.latitude, da.earthml.guessed_dims.longitude

    da = da.sel(
        {
            leadtime_dim: lead_value,
            period_dim: start_period,
        }
    ).squeeze(drop=True)

    if significance is not None:
        if plot_kind != "maps":
            raise ValueError(
                "Significance stippling is currently supported only "
                "for plot_kind='maps'."
            )

        selectors = {}

        if leadtime_dim in significance.dims:
            selectors[leadtime_dim] = lead_value

        if period_dim in significance.dims:
            selectors[period_dim] = start_period

        if selectors:
            significance = significance.sel(
                selectors
            )

        significance = significance.squeeze(drop=True)

    if plot_kind == "maps":
        required_dims = (lat, lon)

    elif plot_kind == "time_lon":
        required_dims = (time_dim, lon)

    elif plot_kind == "time_lat":
        required_dims = (time_dim, lat)

    else:
        raise ValueError(
            f"Unsupported plot_kind={plot_kind!r}. "
            "Choose one of: 'maps', 'time_lon', 'time_lat'."
        )

    missing_dims = [dim for dim in required_dims if dim not in da.dims]
    if missing_dims:
        raise ValueError(
            f"Cannot create {plot_kind!r} plot. "
            f"Missing dimensions: {missing_dims}. "
            f"Available dimensions: {da.dims}"
        )

    extra_dims = [
        dim
        for dim in da.dims
        if dim not in required_dims
    ]
    if extra_dims:
        raise ValueError(
            f"Unexpected dimensions remain before plotting: {extra_dims}. "
            f"Expected only {required_dims}, got {da.dims}."
        )

    if significance is not None:
        missing_sig_dims = [
            dim
            for dim in required_dims
            if dim not in significance.dims
        ]

        if missing_sig_dims:
            raise ValueError(
                f"Significance field is missing dimensions "
                f"{missing_sig_dims}. "
                f"Available dimensions: {significance.dims}"
            )

        significance = significance.transpose(
            *required_dims
        )

        da, significance = xr.align(
            da,
            significance,
            join="exact",
        )

        with ProgressBar():
            da = da.transpose(*required_dims).compute()
            significance = significance.compute()

    else:
        with ProgressBar():
            da = da.transpose(*required_dims).compute()

    if is_skill:
        if improvement_unit in {"%", "normalized"}:
            plot_unit = "%" if improvement_unit == "%" else ""
            scale = 1.0

        else:
            plot_unit, scale = get_plot_metric_unit_and_scale(
                da,
                var=var,
                metric=metric,
                var_plot_config=var_plot_config,
            )

    else:
        plot_unit, scale = get_plot_metric_unit_and_scale(
            da,
            var=var,
            metric=metric,
            var_plot_config=var_plot_config,
        )

    if force_scale is not None:
        scale = force_scale

    da = da / scale

    if is_skill_metric(metric) and not is_skill:
        unit_label = ""
        cb_label = METRIC_NAMES[metric]

    elif is_skill:
        if improvement_unit == "%":
            unit_label = "(%)"
            cb_label = f"{METRIC_NAMES[metric]} improvement"

        elif improvement_unit == "Δ":
            unit_label = f"({plot_unit})" if plot_unit else ""
            cb_label = (
                f"{METRIC_NAMES[metric]} improvement difference "
                f"{unit_label}"
            )

        elif improvement_unit == "normalized":
            unit_label = ""
            cb_label = (
                f"{METRIC_NAMES[metric]} normalized improvement"
            )

    else:
        unit_label = f"({plot_unit})" if plot_unit else ""
        cb_label = (
            f"{METRIC_NAMES[metric]} {unit_label}"
            if unit_label
            else METRIC_NAMES[metric]
        )

    avg = float(da.mean(skipna=True).values)

    if plot_kind == "maps":
        geo_avg = float(da.earthml.geo_mean().values)
    else:
        geo_avg = None

    cmap, norm, ticks = metric_style(
        var,
        metric,
        da,
        var_plot_config=var_plot_config,
        impro_plot_config=impro_plot_config,
        is_skill=is_skill,
        improvement_unit=improvement_unit,
    )

    if plot_kind == "maps":
        lon_values = np.asarray(da[lon].values, dtype=float)
        lat_values = np.asarray(da[lat].values, dtype=float)

        finite_lon = lon_values[np.isfinite(lon_values)]
        finite_lat = lat_values[np.isfinite(lat_values)]

        if finite_lon.size == 0 or finite_lat.size == 0:
            raise ValueError(
                "Latitude or longitude coordinates contain no finite values"
            )

        lon_min = float(finite_lon.min())
        lon_max = float(finite_lon.max())
        lat_min = float(finite_lat.min())
        lat_max = float(finite_lat.max())

        lon_span = lon_max - lon_min
        lat_span = lat_max - lat_min

        # PlateCarree displayed aspect ratio.
        map_aspect = lon_span / lat_span

        # Fixed width, automatic height.
        fig_width = 10.0

        # Height required by the map itself + room for title/colorbar.
        map_height = fig_width / map_aspect
        fig_height = map_height + 1.4

        # Avoid pathological figures for unusual regional domains.
        fig_height = float(np.clip(fig_height, 3.2, 7.0))

        fig, ax = plt.subplots(
            figsize=(fig_width, fig_height),
            subplot_kw={"projection": ccrs.PlateCarree()},
        )
        ax = cast(GeoAxes, ax)
        ax.set_anchor("N")

        if lon_span >= 350.0 and lat_span >= 170.0:
            ax.set_global()

        elif lon_span >= 350.0:
            ax.set_extent(
                [-180.0, 180.0, lat_min, lat_max],
                crs=ccrs.PlateCarree(),
            )

        else:
            ax.set_extent(
                [lon_min, lon_max, lat_min, lat_max],
                crs=ccrs.PlateCarree(),
            )

        if plot_type == "pcolormesh":
            im = ax.pcolormesh(
                da[lon],
                da[lat],
                da,
                transform=ccrs.PlateCarree(),
                cmap=cmap,
                norm=norm,
                shading="auto",
            )

        elif plot_type == "contourf":
            from cartopy.util import add_cyclic_point

            finite_da = da.where(np.isfinite(da))

            data_cyclic, lon_cyclic = add_cyclic_point(
                finite_da.values,
                coord=finite_da[lon].values,
                axis=finite_da.get_axis_num(lon),
            )

            im = ax.contourf(
                lon_cyclic,
                finite_da[lat].values,
                data_cyclic,
                levels=ticks,
                transform=ccrs.PlateCarree(),
                cmap=cmap,
                norm=norm,
                extend="both",
            )

        else:
            raise ValueError(
                f"Unsupported plot_type={plot_type!r}. "
                "Choose one of: 'pcolormesh', 'contourf'."
            )

        # ----------------------------------------------------------
        # Statistical significance stippling
        # ----------------------------------------------------------

        if significance is not None:
            if significance_stride < 1:
                raise ValueError(
                    "significance_stride must be >= 1."
                )

            sig = significance.astype(bool)

            # Downsample the stippling only, not the significance test.
            sig = sig.isel(
                {
                    lat: slice(None, None, significance_stride),
                    lon: slice(None, None, significance_stride),
                }
            )

            lon_sig, lat_sig = np.meshgrid(
                sig[lon].values,
                sig[lat].values,
            )

            mask = np.asarray(
                sig.values,
                dtype=bool,
            )

            finite = (
                np.isfinite(lon_sig)
                & np.isfinite(lat_sig)
            )

            mask &= finite

            ax.scatter(
                lon_sig[mask],
                lat_sig[mask],
                s=significance_size,
                marker=".",
                color="black",
                alpha=significance_alpha,
                linewidths=0,
                transform=ccrs.PlateCarree(),
                zorder=4,
            )

        add_spatial_regions(
            ax,
            regions,
        )

        ax.coastlines(linewidth=0.7)
        ax.add_feature(cfeature.BORDERS, linewidth=0.3)

        gl = ax.gridlines(
            crs=ccrs.PlateCarree(),
            draw_labels=True,
            linewidth=0.5,
            color="gray",
            alpha=0.4,
            linestyle="--",
        )

        gl.top_labels = False
        gl.right_labels = False
        gl.xformatter = LONGITUDE_FORMATTER
        gl.yformatter = LATITUDE_FORMATTER
        if tick_size is not None:
            gl.xlabel_style = {"size": tick_size}
            gl.ylabel_style = {"size": tick_size}

    else:
        fig, ax = plt.subplots(
            figsize=(9, 5.5),
        )

        if plot_kind == "time_lon":
            x_dim = lon
            x_label = "Longitude"
        else:
            x_dim = lat
            x_label = "Latitude"

        finite_da = da.where(np.isfinite(da))

        if plot_type == "pcolormesh":
            im = ax.pcolormesh(
                finite_da[x_dim],
                finite_da[time_dim],
                finite_da,
                cmap=cmap,
                norm=norm,
                shading="auto",
            )

        elif plot_type == "contourf":
            im = ax.contourf(
                finite_da[x_dim],
                finite_da[time_dim],
                finite_da,
                levels=ticks,
                cmap=cmap,
                norm=norm,
                extend="both",
            )

        else:
            raise ValueError(
                f"Unsupported plot_type={plot_type!r}. "
                "Choose one of: 'pcolormesh', 'contourf'."
            )

        if plot_labels:
            ax.set_xlabel(x_label, fontsize=label_size)

        if clim_period == ClimPeriod.MONTH:
            if plot_labels:
                ax.set_ylabel("Month", fontsize=label_size)
            ax.set_yticks(np.arange(1, 13))
            ax.set_yticklabels(
                ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
            )
        else:
            if plot_labels:
                ax.set_ylabel("Time", fontsize=label_size)

        ax.tick_params(axis="both", labelsize=tick_size)
        ax.grid(True, alpha=0.2)

        if plot_kind == "time_lon":
            ax.set_xlim(
                float(finite_da[lon].min()),
                float(finite_da[lon].max()),
            )

        else:
            ax.set_ylim(
                finite_da[time_dim].min().values,
                finite_da[time_dim].max().values,
            )

    label_lt = lead_label(
        da,
        lead_value,
        leadtime_dim,
    )

    start_time = datetime.strptime(
        time_range[0],
        "%Y-%m-%d",
    ).strftime(title_strftime)

    end_time = datetime.strptime(
        time_range[1],
        "%Y-%m-%d",
    ).strftime(title_strftime)

    if plot_kind == "maps":
        summary = (
            f"avg={avg:.3f} {unit_label} · "
            f"geoavg={geo_avg:.3f} {unit_label}"
        )
    else:
        summary = f"avg={avg:.3f} {unit_label}"

    plot_kind_label = {
        "maps": "maps",
        "time_lon": "time-longitude",
        "time_lat": "time-latitude",
    }[plot_kind]

    title = (
        f"{VARIABLE_NAMES[var]} · {model} · {plot_kind_label} · "
        f"{start_time}-{end_time} · {period_dim}={start_period}\n"
        f"leadtime={label_lt} {leadtime_units} · {summary}"
    )

    if plot_title:
        if plot_kind == "maps":
            fig.suptitle(
                title,
                fontsize=title_size,
                y=0.98,
                linespacing=1.05,
            )
            fig.subplots_adjust(
                top=0.91,
                bottom=0.20,
                left=0.06,
                right=0.97,
            )
        else:
            ax.set_title(
                title,
                pad=10,
                fontsize=title_size,
            )
    else:
        if plot_kind == "maps":
            fig.subplots_adjust(
                top=0.97,
                bottom=0.15,
                left=0.06,
                right=0.97,
            )

    if plot_kind == "maps":
        cb = add_max_size_colorbar(
            fig,
            ax,
            im,
            ticks=ticks,
        )
    else:
        cb = fig.colorbar(
            im,
            ax=ax,
            orientation="horizontal",
            pad=0.13,
            fraction=0.15,
            aspect=20,
            ticks=ticks,
        )

    if plot_labels:
        cb.set_label(
            cb_label,
            fontsize=label_size,
        )

    cb.ax.xaxis.set_major_formatter(
        FuncFormatter(smart_tick_formatter(ticks))
    )

    adapt_colorbar_tick_sizes(
        fig,
        cb,
        tick_size=tick_size,
    )

    out_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fig.savefig(
        out_file,
        dpi=dpi,
    )

    plt.close(fig)


def plot_rank_histogram(
    das: Sequence[xr.DataArray | xr.Dataset],
    *,
    var: str,
    metric: str,
    models: str | Sequence[str],
    start_period: str | int,
    out_file: Path,
    time_range: tuple[str, str],
    rank_dim: str = "rank",
    plot_title: bool = True,
    plot_labels: bool = True,
    title_size: float | None = None,
    label_size: float | None = None,
    tick_size: float | None = None,
    dpi: int = 200,
) -> None:
    if isinstance(models, str):
        models = [models]
    if len(models) != len(das):
        raise ValueError("Select same number of models and DataArrays")

    fig, ax = plt.subplots(figsize=(8, 4.8))
    for da, model in zip(convert_to_da_list(das, var), models):
        if rank_dim not in da.dims:
            print(f"Skipping rank histogram: no {rank_dim!r} in {da.dims}")
            return

        reduce_dims = [dim for dim in da.dims if dim != rank_dim]

        if reduce_dims:
            da = da.sum(dim=reduce_dims, skipna=True)

        with ProgressBar():
            da = da.compute()

        ax.bar(
            da[rank_dim].values,
            da.values,
            width=0.8,
            color=MODEL_COLORS.get(model, None),
            alpha=0.6,
            label=model,
        )

    start_time = datetime.strptime(time_range[0], "%Y-%m-%d").strftime("%Y")
    end_time = datetime.strptime(time_range[1], "%Y-%m-%d").strftime("%Y")
    if plot_title:
        ax.set_title(
            f"{VARIABLE_NAMES[var]} · {METRIC_NAMES[metric]} · "
            f"{start_time}-{end_time} · start month={start_period}",
            fontsize=title_size,
        )

    if plot_labels:
        ax.set_xlabel(rank_dim, fontsize=label_size)
        ax.set_ylabel("count", fontsize=label_size)
    ax.tick_params(axis="both", labelsize=tick_size)
    ax.grid(True, alpha=0.3)
    ax.legend()

    out_file.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(out_file, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


@dataclass(frozen=True)
class ScatterPoint:
    x: float
    y: float
    variable: str
    region: str
    leadtime: object
    start_month: object
    total_months: object
    experiment: str


def get_total_months(s: Settings) -> object:
    for name in ("total_months", "history_months", "input_months", "context_months"):
        if hasattr(s, name):
            return getattr(s, name)
    return "all"


def lighten(color, amount: float):
    r, g, b = to_rgb(color)
    return (
        r + (1 - r) * amount,
        g + (1 - g) * amount,
        b + (1 - b) * amount,
    )


def point_field(p: ScatterPoint, field: str):
    return getattr(p, field)


def plot_metric_diff_scatter(
    points: Sequence[ScatterPoint],
    *,
    forecast_metric: str,
    diff_metric: str,
    out_file: Path,
    color_by: str = "variable",
    marker_by: str = "leadtime",
    shade_by: str = "total_months",
    title: str | None = None,
    xlabel: str | None = None,
    ylabel: str | None = None,
    figsize=(12, 12),
    cmap_name: str = "tab10",
    markers=("o", "s", "^", "D", "v", "P", "X"),
    point_size: float = 22,
    edgecolor: str = "black",
    linewidth: float = 0.3,
    shade_strength: float = 0.65,
    fit_lines: bool = True,
    fit_min_points: int = 3,
    shade_improvement_region: bool = True,
    plot_title: bool = True,
    plot_labels: bool = True,
    title_size: float | None = None,
    label_size: float | None = None,
    tick_size: float | None = None,
    dpi: int = 200,
) -> None:
    fig, ax = plt.subplots(figsize=figsize)

    if not points:
        if plot_title:
            ax.set_title(title or "No data", fontsize=title_size)

        if plot_labels:
            ax.set_xlabel(
                xlabel or f"{diff_metric} improvement",
                fontsize=label_size,
            )
            ax.set_ylabel(
                ylabel or forecast_metric,
                fontsize=label_size,
            )
        ax.tick_params(axis="both", labelsize=tick_size)
        ax.grid(alpha=0.3)
        out_file.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(out_file, dpi=dpi, bbox_inches="tight")
        plt.close(fig)
        return

    color_values = sorted({point_field(p, color_by) for p in points}, key=str)
    marker_values = sorted({point_field(p, marker_by) for p in points}, key=str)
    shade_values = sorted({point_field(p, shade_by) for p in points}, key=str)

    cmap = plt.get_cmap(cmap_name)

    def base_color(value):
        idx = color_values.index(value)
        return cmap(idx % cmap.N)

    for color_value in color_values:
        base = base_color(color_value)

        for shade_i, shade_value in enumerate(shade_values):
            denom = max(1, len(shade_values) - 1)
            shade = lighten(base, shade_strength * shade_i / denom)

            for marker_i, marker_value in enumerate(marker_values):
                subset = [
                    p for p in points
                    if point_field(p, color_by) == color_value
                    and point_field(p, shade_by) == shade_value
                    and point_field(p, marker_by) == marker_value
                ]

                if not subset:
                    continue

                ax.scatter(
                    [p.x for p in subset],
                    [p.y for p in subset],
                    color=shade,
                    marker=markers[marker_i % len(markers)],
                    s=point_size,
                    edgecolor=edgecolor,
                    linewidth=linewidth,
                )

    if fit_lines:
        neutral_base = (0.2, 0.2, 0.2)
        linestyles = ["-", "--", ":", "-."]

        for shade_i, shade_value in enumerate(shade_values):
            denom = max(1, len(shade_values) - 1)
            line_color = lighten(neutral_base, shade_strength * shade_i / denom)

            for marker_i, marker_value in enumerate(marker_values):
                subset = [
                    p for p in points
                    if point_field(p, shade_by) == shade_value
                    and point_field(p, marker_by) == marker_value
                ]

                if len(subset) < fit_min_points:
                    continue

                x = np.asarray([p.x for p in subset], dtype=float)
                y = np.asarray([p.y for p in subset], dtype=float)

                mask = np.isfinite(x) & np.isfinite(y)
                if mask.sum() < fit_min_points or np.allclose(x[mask], x[mask][0]):
                    continue

                a, b = np.polyfit(x[mask], y[mask], 1)
                xs = np.linspace(x[mask].min(), x[mask].max(), 200)

                ax.plot(
                    xs,
                    a * xs + b,
                    color=line_color,
                    linestyle=linestyles[marker_i % len(linestyles)],
                    linewidth=1.0,
                    alpha=0.9,
                )

    ax.axvline(0, color="black", alpha=0.5, linewidth=0.8)

    ax.set_xlabel(
        xlabel or f"{METRIC_NAMES.get(diff_metric, diff_metric)} improvement",
        fontsize=label_size,
    )
    ax.set_ylabel(
        ylabel or METRIC_NAMES.get(forecast_metric, forecast_metric),
        fontsize=label_size,
    )
    ax.tick_params(axis="both", labelsize=tick_size)

    if title is not None:
        ax.set_title(title, fontsize=title_size)

    ax.grid(alpha=0.3)

    handles: list[Line2D] = []

    handles.append(Line2D([], [], linestyle="None", label=color_by.replace("_", " ").title()))
    for value in color_values:
        handles.append(
            Line2D(
                [0], [0],
                marker="o",
                linestyle="None",
                markersize=7,
                markerfacecolor=base_color(value),
                markeredgecolor=edgecolor,
                label=str(value),
            )
        )

    handles.append(Line2D([], [], linestyle="None", label=shade_by.replace("_", " ").title()))
    neutral_base = (0.2, 0.2, 0.2)
    denom = max(1, len(shade_values) - 1)
    for i, value in enumerate(shade_values):
        handles.append(
            Line2D(
                [0], [0],
                marker="o",
                linestyle="None",
                markersize=7,
                markerfacecolor=lighten(neutral_base, shade_strength * i / denom),
                markeredgecolor=edgecolor,
                label=str(value),
            )
        )

    handles.append(Line2D([], [], linestyle="None", label=marker_by.replace("_", " ").title()))
    for i, value in enumerate(marker_values):
        handles.append(
            Line2D(
                [0], [0],
                marker=markers[i % len(markers)],
                linestyle="None",
                markersize=7,
                markerfacecolor="white",
                markeredgecolor="black",
                label=str(value),
            )
        )

    leg = ax.legend(handles=handles, loc="upper left", fontsize=9, frameon=False)

    for txt in leg.get_texts():
        if txt.get_text() in {
            color_by.replace("_", " ").title(),
            shade_by.replace("_", " ").title(),
            marker_by.replace("_", " ").title(),
        }:
            txt.set_weight("bold")

    if shade_improvement_region:
        fig.canvas.draw()

        xmin, xmax = ax.get_xlim()
        ymin, ymax = ax.get_ylim()

        if xmax > 0:
            ax.axvspan(
                0,
                xmax,
                color="green",
                alpha=0.06,
                zorder=0,
            )

        ax.set_xlim(xmin, xmax)
        ax.set_ylim(ymin, ymax)

    out_file.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(out_file, dpi=dpi, bbox_inches="tight")
    plt.close(fig)


def get_plot_unit_and_scale(da: xr.DataArray, var: str) -> tuple[str, float]:
    unit = da.attrs.get("units") or VARIABLE_UNITS.get(var, "")

    unit_conversion = UNIT_CONVERSIONS.get(unit, (unit, 1.0))

    if isinstance(unit_conversion, dict):
        return unit_conversion.get(var, (unit, 1.0))

    return unit_conversion


def normalize_longitudes(da: xr.DataArray, lon_name: str) -> xr.DataArray:
    if float(da[lon_name].max(skipna=True)) <= 180:
        return da

    new_lon = ((da[lon_name] + 180) % 360) - 180
    return da.assign_coords({lon_name: new_lon}).sortby(lon_name)


def prepare_map_da(
    da: xr.DataArray,
    spatial_dims: tuple[str, str] = ("latitude", "longitude"),
) -> xr.DataArray:
    da = da.squeeze(drop=True)
    lat, lon = spatial_dims
    da = normalize_longitudes(da, lon)
    return da.transpose(lat, lon)


def reduce_to_timeseries(
    da: xr.DataArray,
    *,
    spatial_dims: tuple[str, str] = ("latitude", "longitude"),
) -> xr.DataArray:
    reduce_dims = [dim for dim in spatial_dims if dim in da.dims]

    if len(reduce_dims) == 2:
        weights = np.cos(np.deg2rad(da[spatial_dims[0]]))
        return da.weighted(weights).mean(reduce_dims, skipna=True)

    if reduce_dims:
        return da.mean(reduce_dims, skipna=True)

    return da


def plot_field_map(
    da: xr.DataArray,
    *,
    var: str,
    title: str | None = None,
    out_file: Path,
    cmap: str | Colormap | CmapColormap = "viridis",
    centered: bool = False,
    vmin: float | None = None,
    vmax: float | None = None,
    spatial_dims: tuple[str, str] = ("latitude", "longitude"),
    plot_type: Literal["pcolormesh", "contourf"] = "pcolormesh",
    levels: int = 21,
    figsize: tuple[float, float] = (7, 5),
    regions: Sequence[dict] | None = None,
    plot_title: bool = True,
    plot_labels: bool = True,
    title_size: float | None = None,
    label_size: float | None = None,
    tick_size: float | None = None,
    dpi: int = 200,
) -> None:

    if isinstance(cmap, CmapColormap):
        cmap = cmap.to_mpl()
    elif isinstance(cmap, str):
        cmap = CmapColormap(cmap).to_mpl()

    plot_unit, scale = get_plot_unit_and_scale(da, var)
    da = prepare_map_da(
        da / scale,
        spatial_dims=spatial_dims,
    )

    lat, lon = spatial_dims

    fig, ax = plt.subplots(
        figsize=figsize,
        subplot_kw={"projection": ccrs.PlateCarree()},
    )


    # Convert manually supplied limits to plotting units.
    if vmin is not None:
        vmin /= scale

    if vmax is not None:
        vmax /= scale

    norm = None

    if centered:
        if vmin is None or vmax is None:
            abs_max = float(np.nanmax(np.abs(da.values)))
        else:
            abs_max = max(abs(vmin), abs(vmax))

        vmin = -abs_max
        vmax = abs_max

        norm = TwoSlopeNorm(
            vmin=vmin,
            vcenter=0.0,
            vmax=vmax,
        )

    if plot_type == "pcolormesh":
        im = ax.pcolormesh(
            da[lon],
            da[lat],
            da,
            transform=ccrs.PlateCarree(),
            shading="auto",
            cmap=cmap,
            norm=norm,
            vmin=None if norm is not None else vmin,
            vmax=None if norm is not None else vmax,
        )

    elif plot_type == "contourf":
        from cartopy.util import add_cyclic_point

        data, lon_values = add_cyclic_point(
            da.values,
            coord=da[lon].values,
            axis=da.get_axis_num(lon),
        )

        if vmin is None:
            vmin = float(np.nanmin(data))

        if vmax is None:
            vmax = float(np.nanmax(data))

        contour_levels = np.linspace(
            vmin,
            vmax,
            levels,
        )

        im = ax.contourf(
            lon_values,
            da[lat].values,
            data,
            levels=contour_levels,
            transform=ccrs.PlateCarree(),
            cmap=cmap,
            norm=norm,
            extend="both",
        )

    else:
        raise ValueError(
            f"Unsupported plot_type={plot_type!r}. "
            "Choose 'pcolormesh' or 'contourf'."
        )

    add_spatial_regions(
        ax,
        regions,
    )

    ax.coastlines(linewidth=0.7)
    ax.add_feature(cfeature.BORDERS, linewidth=0.3)

    if plot_title and title is not None:
        ax.set_title(title, fontsize=title_size)

    gl = ax.gridlines(draw_labels=True, linewidth=0)
    gl.top_labels = False
    gl.right_labels = False
    if tick_size is not None:
        gl.xlabel_style = {"size": tick_size}
        gl.ylabel_style = {"size": tick_size}

    plt.tight_layout()

    cb = add_max_size_colorbar(
        fig,
        ax,
        im,
    )
    cb.ax.xaxis.set_major_formatter(
        FuncFormatter(smart_tick_formatter(ticks))
    )

    if plot_labels:
        cb.set_label(
            f"{VARIABLE_NAMES.get(var, var.upper())} ({plot_unit})"
            if plot_unit
            else VARIABLE_NAMES.get(var, var.upper()),
            fontsize=label_size,
        )
    cb.ax.tick_params(labelsize=tick_size)

    out_file.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    plt.savefig(
        out_file,
        dpi=dpi,
        bbox_inches="tight",
    )

    print(f"Saved map: {out_file}")

    plt.close(fig)


def plot_field_timeseries(
    *,
    series: dict[str, xr.DataArray | None],
    member_series: dict[str, xr.DataArray | None] | None,
    var: str,
    title: str | None = None,
    out_file: Path,
    time_dim: str = "time",
    spatial_dims: tuple[str, str] = ("latitude", "longitude"),
    realization_dim: str = "realization",
    spread: Literal["std", "minmax"] = "std",
    val_end: str | None = None,
    train_end: str | None = None,
    plot_single_members: bool = True,
    member_linestyle: str = "-",
    series_linestyle: str = "--",
    series_offsets: dict[str, float] | None = None,
    plot_title: bool = True,
    plot_labels: bool = True,
    title_size: float | None = None,
    label_size: float | None = None,
    tick_size: float | None = None,
    dpi: int = 200,
) -> None:
    valid = {name: da for name, da in series.items() if da is not None}

    valid_members = {
        name: da
        for name, da in (member_series or {}).items()
        if da is not None and realization_dim in da.dims
    }

    if not valid and not valid_members:
        return

    first = next(iter(list(valid.values()) + list(valid_members.values())))

    plot_unit, scale = get_plot_unit_and_scale(first, var)

    ylabel = (
        f"{VARIABLE_NAMES.get(var, var.upper())} ({plot_unit})"
        if plot_unit
        else VARIABLE_NAMES.get(var, var.upper())
    )

    reduced = {
        name: reduce_to_timeseries(da / scale, spatial_dims=spatial_dims)
        for name, da in valid.items()
    }

    reduced_members = {}
    if member_series is not None:
        for name, da in member_series.items():
            if da is not None and realization_dim in da.dims:
                reduced_members[name] = reduce_to_timeseries(
                    da / scale,
                    spatial_dims=spatial_dims,
                )

    # Align everything together on the same time axis
    all_names = list(reduced.keys()) + [f"__members__{k}" for k in reduced_members]
    all_arrays = list(reduced.values()) + list(reduced_members.values())

    aligned = xr.align(*all_arrays, join="inner")

    aligned_map = dict(zip(all_names, aligned))

    reduced = {
        name: aligned_map[name]
        for name in reduced
    }

    reduced_members = {
        name: aligned_map[f"__members__{name}"]
        for name in reduced_members
    }

    fig, ax = plt.subplots(figsize=(16, 8))

    if series_offsets:
        for name, offset in series_offsets.items():
            color = SERIES_COLORS.get(name)

            ax.axhline(
                offset,
                color=color,
                linewidth=1,
                alpha=0.35,
                linestyle="--",
                zorder=0,
            )

    plot_names = list(dict.fromkeys([*reduced.keys(), *reduced_members.keys()]))

    for name in plot_names:
        color = SERIES_COLORS.get(name)
        da = reduced.get(name)
        member_da = reduced_members.get(name)

        offset = 0.0 if series_offsets is None else series_offsets.get(name, 0.0)

        if da is not None:
            x = da[time_dim].values
        elif member_da is not None:
            x = member_da[time_dim].values
        else:
            continue

        if member_da is not None:
            with ProgressBar():
                member_da = member_da.compute()

            if plot_single_members:
                for i in range(member_da.sizes[realization_dim]):
                    member_da_i = member_da.isel({realization_dim: i})

                    ax.plot(
                        x,
                        member_da_i.values + offset,
                        linestyle=member_linestyle,
                        linewidth=0.5,
                        alpha=0.2,
                        color=color,
                    )

            member_mean = member_da.mean(realization_dim, skipna=True)

            # Spread setting and validation
            if spread == "std":
                member_std = member_da.std(
                    realization_dim,
                    skipna=True,
                )
                lower = member_mean - member_std
                upper = member_mean + member_std

            elif spread == "minmax":
                lower = member_da.min(
                    realization_dim,
                    skipna=True,
                )
                upper = member_da.max(
                    realization_dim,
                    skipna=True,
                )

            else:
                raise ValueError(
                    f"Unsupported spread={spread!r}. "
                    "Choose 'std' or 'minmax'."
                )

            ax.fill_between(
                x,
                lower.values + offset,
                upper.values + offset,
                alpha=0.18,
                color=color,
            )

            ax.plot(
                x,
                member_mean.values + offset,
                linestyle=member_linestyle,
                linewidth=1.4,
                color=color,
                label=f"{name} member mean",
            )

        if da is not None:
            with ProgressBar():
                da = da.compute()

            ax.plot(
                x,
                da.values + offset,
                linewidth=1.4,
                linestyle=series_linestyle,
                color=color,
                label=name,
            )

    if train_end is not None:
        ax.axvline(
            np.datetime64(train_end),
            color="red",
            linestyle="--",
            linewidth=1.3,
            label="Train end",
        )

    if val_end is not None:
        ax.axvline(
            np.datetime64(val_end),
            color="blue",
            linestyle="--",
            linewidth=1.3,
            label="Val end",
        )

    if plot_title and title is not None:
        ax.set_title(title, fontsize=title_size)

    if plot_labels:
        ax.set_xlabel(time_dim, fontsize=label_size)
        ax.set_ylabel(ylabel, fontsize=label_size)
    ax.tick_params(axis="both", labelsize=tick_size)
    ax.grid(True, alpha=0.3)
    ax.legend()

    if series_offsets:
        ax2 = ax.twinx()
        ax2.set_ylim(ax.get_ylim())

        tick_names = [n for n in plot_names if n in series_offsets]
        ax2.set_yticks([series_offsets[n] for n in tick_names])
        tick_zeros = ["0" for n in plot_names if n in series_offsets]

        ax2.set_yticklabels(tick_zeros)
        ax2.tick_params(axis="y", labelsize=tick_size)

        for label, name in zip(ax2.get_yticklabels(), tick_names):
            label.set_color(SERIES_COLORS.get(name))

    out_file.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(out_file, dpi=dpi, bbox_inches="tight")
    print(f"Saved timeseries: {out_file}")
    plt.close(fig)
